# Generated by Django 3.0.5 on 2020-12-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productdate', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.CharField(max_length=50)),
                ('high', models.DecimalField(decimal_places=5, max_digits=7)),
                ('low', models.DecimalField(decimal_places=5, max_digits=7)),
                ('open', models.DecimalField(decimal_places=5, max_digits=7)),
                ('close', models.DecimalField(decimal_places=5, max_digits=7)),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
