# Generated by Django 3.0.5 on 2020-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0002_auto_20201214_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlytable',
            name='index',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
